services:
  app:
    build: .
    image: orpheus
    container_name: orpheus-experiment-engine
    ports:
      - "8000:8000"   # host:container
    volumes:
      - ./saved_experiment_params:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
